### PR TITLE
Remove apparently inert TracingSubscriber and hooks instrumentation

### PR DESCRIPTION
**Pull request by richardstartin**
Either the `TracingSubscriber` doesn't do anything or its effect is not tested - its removal does not lead to a single failed test. As far as I can tell, it just activates the active span over and over again which creates a lot of overhead, and leads to stack traces like this:
Screenshot 2021-03-01 at 19 08 55

If this PR should not be merged, we need a test case which would fail on this branch but not on master.

### CODE REVIEW

**Comment by lpriima** [comment]
I would consider auto approve for red-only not test code :
image

**Review by lpriima — APPROVED** [review]

**Comment by richardstartin** [comment]
I had to test this manually (without setting up a redis cluster), I get identical trace structures, except a trace is suppressed with the hook advice active:

master
```
[netty.request[Controller.hits][redis.query[netty.connect]]]
[netty.request[FilteringWebHandler.handle][netty.client.request]]
```

this branch
```
[netty.request[Controller.hits][redis.query[netty.connect]]]
[netty.request[FilteringWebHandler.handle][netty.client.request]]
[netty.request[ResourceWebHandler.handle]]
```

**Comment by devinsba** [comment]
The `ResourceWebHandler` one seems really odd. I can't think of a reason there would be 3 traces, unless the context is getting lost somewhere.

**Review by devinsba — APPROVED** [review]
I think we should probably hold on merging this until we understand the `ResourceWebHandler` thing but it makes sense otherwise

**Comment by richardstartin** [comment]
@devinsba I think I got to the bottom of it - it's loading the error page

**Review by tylerbenson — APPROVED** [review]

**Pull request closed without merging**
