### PR TITLE
Add workflow for Update Gradle Wrapper Action.

### PR DESCRIPTION
**Pull request by cristiangreco**
Hey there 👋, first of all thanks for your work on the APM for Java!

I've got a suggested change: would you be willing to use [this GitHub Action](https://github.com/gradle-update/update-gradle-wrapper-action) to automatically keep Gradle Wrapper updated to latest release?

**What does "Update Gradle Wrapper Action" do?** It can be configured to run at scheduled intervals (e.g. daily or weekly) and will check whether the Wrapper script in the repo is up-to-date to the latest Gradle release: in case a new Gradle version is available, it will create a PR to update the Wrapper. And that's it!

**Why is that a good thing?** Well, first of all it alleviates the chore of manually updating the Wrapper, as you got a task that keeps track of new Gradle releases for you! More importantly, it boosts security around the Wrapper update and usage processes: this actions verifies that the `gradle-wrapper.jar` file has not been tampered with (uses checksum comparison), and it sets the `distributionSha256Sum` property so that the new Gradle binary itself will be verified locally upon download.

**Where can I find more about?** The [README](https://github.com/gradle-update/update-gradle-wrapper-action/blob/master/README.md) contains quite detailed information!

In this PR I propose adding a new workflow which runs the action every day at midnight (but feel free to adjust the frequency as you prefer). I've verified it works correctly in my fork of the repo: as your Wrapper is already up-to-date in this moment, [you can see here](https://github.com/gradle-update/dd-trace-java/actions/runs/281426928) that the action detects no changes are needed. However, you can see an example of an automated PR in [other projects](https://github.com/ankidroid/Anki-Android/pull/7229) using the action.

The action is under active development, you can have a look at the [list of inputs](https://github.com/gradle-update/update-gradle-wrapper-action#action-inputs) currently supported. There's new features coming up soon and if you'd like to request any particular change just let me know!

I'd love to see the action used by your project and I genuinely hope you can find this useful. Would love your feedback! ❤️

### CODE REVIEW

**Review by richardstartin — CHANGES_REQUESTED** [review]
Hi @cristiangreco - looks really good, but since it's a third party action, we need a SHA rather than a version, just in case. :)

**Comment by cristiangreco** [comment]
@richardstartin thanks for your reply! 

Yeah it makes sense to use a sha ref if you want to stay on the safe side. You might not automatically benefit from new functionalities or fixes if you don't use `v1`, but I totally understand that you want to have more control over a 3rd party repo. Will update this PR to point to the sha of the latest release. 🙂

**Comment by tylerbenson** [comment]
I'm curious what an example PR would look like.

**Comment by cristiangreco** [comment]
> I'm curious what an example PR would look like.

@tylerbenson you can see some PRs [here](https://github.com/dnsimple/dnsimple-java/pull/84) and [here](https://github.com/vector-im/element-android/pull/2193). I couldn't produce an example PR for your project because it's already up-to-date to latest Gradle version. 🙂

**Comment by cristiangreco** [comment]
Hey @richardstartin @tylerbenson I've updated the workflow to pin the action version to sha `74a035c` (it's the one that corresponds to latest release, v1.0.9). Let me know if this works for you 🙂

**Review by bantonsson — APPROVED** [review]

**Review by richardstartin — APPROVED** [review]

**Review by tylerbenson — APPROVED** [review]
@cristiangreco feature request... can the PR that gets submitted also include a link to `https://gradle.org/release-checksums/` to simplify the checksum validation?

**Comment by cristiangreco** [comment]
> @cristiangreco feature request... can the PR that gets submitted also include a link to `https://gradle.org/release-checksums/` to simplify the checksum validation?

Good idea, will do!

**Pull request merged**
