### PR TITLE
Remove Jackson from AWS Helper class

### PR DESCRIPTION
**Pull request by realark**
Referencing core agent classes in helper classes can lead to class load exceptions because those classes won't always be available on the classloader the helper is injected on.

### CODE REVIEW

**Comment by tylerbenson** [comment]
Why was Jackson on the class path at all?

**Comment by realark** [comment]
It was being used as a one-liner to parse the aws request headers into a string for the `params` tag.

**Comment by tylerbenson** [comment]
No, I understand that. I’m wondering how the dependency got onto the classpath. Is it a transitive dependency from AWS?

**Comment by realark** [comment]
Yep, looks like it's a transitive dependency from aws. Our shadow rules renamed it to the datadog prefix, then the recent classloader overhaul made those datadog deps unreachable.

**Pull request merged**
