### PR TITLE
Fix rmic Gradle task

### PR DESCRIPTION
**Pull request by monosoul**
# What Does This Do
Makes `rmic` Gradle task use `rmic` binary provided with Java 8 toolchain. Also changes the task type to `Exec` and refactors the command a bit.

Also, this ( 6b3bea360ec2fdb4606eed4c8e058332393781a1 ) makes the paths to resolve properly on Windows (or any other OS). Not sure if the rest of the project will work properly on Windows, but this part will work now. :slightly_smiling_face: 

# Motivation
Without this change the task will fail if `rmic` binary is not on the Path env var. 
This is bad for 2 reasons:

- [Contribution guide](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md) doesn't mention anywhere it has to be on the path.
- Makes the build unpredictable. Since the rest of the modules are built with Java 8, it's better to explicitly specify the toolchain to use here.

# Additional Notes
Without this change I couldn't even import this project in IntelliJ.

### CODE REVIEW

**Review by devinsba — APPROVED** [review]
LGTM, Thanks for the contribution!

**Comment by monosoul** [comment]
Hey @devinsba , thanks for reviewing it! It seems like the CI doesn't work from my fork. So what happens next? How to run the CI with this branch to make sure everything still works? And how to get this merged?

**Comment by devinsba** [comment]
I'm just waiting for a second review. We will have to probably run locally before merging

**Comment by bantonsson** [comment]
I think that @monosoul needs to allow CircleCI to access his fork by signing in to [CircleCI](https://app.circleci.com/), but I could be wrong.

**Comment by monosoul** [comment]
k, let me try to trigger the pipeline

**Comment by monosoul** [comment]
k, now I need someone to approve the workflows

**Comment by bantonsson** [comment]
Thanks @monosoul. I tried to just allow the workflows, but CircleCI seems very stubborn. I'll close and reopen this PR to see if that does the trick.

**Comment by monosoul** [comment]
@bantonsson no worries, I'm happy to help troubleshoot it. I'll try a PR with a new branch

**Pull request closed without merging**
