### PR TITLE
Add Reiterating RedefinitionStrategy

### PR DESCRIPTION
**Pull request by tylerbenson**
This ensures that any classes that may have been loaded by the agent in the process of transforming will also be given a chance to be instrumented in a subsequent pass.

This also allows us to enable the Cassandra async callback test, which otherwise fails without this change.

### CODE REVIEW

**Comment by richardstartin** [comment]
Do we have a test case where this happens so we can understand how it affects the application?

**Comment by tylerbenson** [comment]
@Trask said [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1089#discussion_r475737063) that it allowed him to enable Cassandra async test, but I wasn't able to get it working.  Either way it seemed like a more correct configuration.

**Review by richardstartin — CHANGES_REQUESTED** [review]
This needs a test

**Review by richardstartin — APPROVED** [review]
Approving on the basis that the cassandra async test doesn't fail once during the build

**Comment by tylerbenson** [comment]
This is making the Java 7 build sad.  It seems like it's using more memory and causing the test to get OOM killed (exit 137).

**Comment by tylerbenson** [comment]
Java 7 seems to be in a better place now.  Marking for review again.

**Review by randomanderson — APPROVED** [review]
My one small concern is if there's a potential performance hit

**Pull request merged**
