### PR TITLE
Support jetty client 12

### PR DESCRIPTION
**Pull request by amarziali**
# What Does This Do

Instrument jetty client 12+

# Motivation

See #7300 

# Additional Notes

Jira ticket: [PROJ-IDENT]

### CODE REVIEW

**Review by vandonr — COMMENTED** [review]
This is a bit hard to review... I can diff those files locally with the 10.0 instrumentation, but maybe you can point to the things you had to change for this instrumentation ?

**Review by nayeem-kamal — APPROVED** [review]
Overall LGTM. As @vandonr 's comment states. Maybe you could just add a bit in the description or in a comment about what the changes are from previous versions.

**Comment by amarziali** [comment]
> This is a bit hard to review... I can diff those files locally with the 10.0 instrumentation, but maybe you can point to the things you had to change for this instrumentation ?

The request/response classes have a package change as well the way the span completion listener is applied differs

**Comment by vandonr** [comment]
For a future case like this, what we can do is do a first commit where the files are just copied, and then a commit where the changes are done. This allows reviewing the changes by looking at the second commit only.

**Pull request merged**
