### PR TITLE
[WIP] Gradle 7.6

### PR DESCRIPTION
**Pull request by mcculls**
https://docs.gradle.org/7.6/release-notes.html

### CODE REVIEW

**Comment by bantonsson** [comment]
@mcculls I never got around to opening an issue or PR with my memory patches, and I think they haven't been fixed by anyone else. Is there anything we need urgently, or can I do a patched release later? Yes, I'll open an issue for discussion about my proposed fixes on [gradle](https://github.com/gradle/gradle) as well.

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed
```

**Comment by mcculls** [comment]
@bantonsson there's a [bug](https://github.com/gradle/gradle/issues/21542) in 7.5.x where a build failure also leads to a `StackOverflowError` canceling tasks - it's not urgent because it only happens when the build fails for another reason, but it can be distracting

**Comment by bantonsson** [comment]
Ah, ok. I'll kick off a build in the background.

**Review by bantonsson — APPROVED** [review]

**Comment by mcculls** [comment]
Note this branch passes the functional tests, but for some reason the build time is much longer compared to Gradle 7.5

**Comment by bantonsson** [comment]
I think it could be related to the build cache not being saved/used properly.

**Comment by mcculls** [comment]
Note I can recreate the build time difference locally, so it's not limited to CI

**Comment by bantonsson** [comment]
Interesting...

**Comment by mcculls** [comment]
Turns out there are several regressions in 7.6 involving increased memory usage which [7.6.1](https://github.com/gradle/gradle/milestone/220) will fix

**Comment by bantonsson** [comment]
Looks like neither gradle/gradle#23944 nor gradle/gradle#23912 was backported to 7.6.1, so we need to patch yet again...

**Comment by mcculls** [comment]
At this point I'm ok waiting for those to show up in a proper release...

**Comment by bantonsson** [comment]
Looks like 8.1 right now.

**Pull request closed without merging**
