### PR TITLE
Add Micronaut NewSpan Tracing Annotation

### PR DESCRIPTION
**Pull request by brianwyka**
Adds Micronaut `@NewSpan` annotation support for tracing methods

- https://docs.micronaut.io/2.0.x/api/io/micronaut/tracing/annotation/NewSpan.html
- https://docs.micronaut.io/latest/guide/index.html#distributedTracing

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]
Thanks for the contribution!

**Comment by brianwyka** [comment]
Thanks @tylerbenson.  Was curious if any of you guys would be able to help with this:
https://github.com/micronaut-projects/micronaut-core/issues/5201

**Comment by tylerbenson** [comment]
@brianwyka I don't know much about micronaut, but from the doc you linked it seems they integrate via OpenTracing.  I believe that means if you use our javaagent or you register a `DDTracer` into the `GlobalTracer`, then it should just work. Though using both together might result in duplicate spans being generated.

**Comment by brianwyka** [comment]
Thanks for the reply @tylerbenson, I'll do a little bit more research.

**Comment by brianwyka** [comment]
@tylerbenson, I tried numerous things to create a `DDTracer` from the `CoreTracer` in `dd-java-agent`, but failed since there is a class relocation during shading of classes.  I am unable to register a tracer "bean" with Micronaut because of this and set it in the open tracing `GlobalTracer`, not the datadog `GlobalTracer`.  

Any thoughts?  Is it possible to perhaps make an update to `dd-java-agent` to register an open tracer compatible tracer and register it?

**Comment by devinsba** [comment]
@brianwyka The opentracing compatible tracer is available with the `dd-trace-ot` artifact

**Comment by brianwyka** [comment]
@devinsba, yes.  However, when using the java agent, a `CoreTracer` implementation is created, which doesn't implement open tracing `Tracer`.  Is that corret?

**Comment by tylerbenson** [comment]
If you're using dd-java-agent then a `GlobalTracer` instance is registered automatically. My comment about using a `DDTracer` only applies if you're not using `dd-java-agent`.  Sorry for the confusion.

**Comment by brianwyka** [comment]
I see this here:
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java#L27

But that is Datadog's global tracer, not the open tracing one.  Am I missing something?

**Comment by tylerbenson** [comment]
@brianwyka we have [instrumentation](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/GlobalTracerInstrumentation.java#L61) in `dd-java-agent` that dynamically registers a `Tracer` instance when `io.opentracing.util.GlobalTracer` is initialized. If you need to pass Micronaut a `Tracer` instance, you can get that via `io.opentracing.util.GlobalTracer.get()` and it should be backed by the Datadog tracer when using the javaagent and a noop instance when not.

**Comment by brianwyka** [comment]
Okay, I will try that @tylerbenson and report back.  Thanks.

**Comment by brianwyka** [comment]
Circling back on this.  Was able to get it to work @tylerbenson .  Thanks for the help.

**Comment by tylerbenson** [comment]
Thanks for the followup.  Glad you got it working. Just to be clear though, I think this would still be a useful annotation for us to support OOTB, don't you?

**Comment by brianwyka** [comment]
@tylerbenson.  Would it conflict with support added in a Micronaut module, or could they be both present and still not conflict?

**Comment by tylerbenson** [comment]
How difficult was it to get working otherwise? Did it happen automatically once you used the OpenTracing link?

**Comment by brianwyka** [comment]
Configuration in java looked like this:

```java
import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Primary;
import io.micronaut.context.annotation.Requires;
import io.micronaut.context.env.Environment;
import io.micronaut.context.exceptions.BeanInstantiationException;
import io.micronaut.tracing.annotation.ContinueSpan;
import io.micronaut.tracing.annotation.NewSpan;
import io.micronaut.tracing.annotation.SpanTag;
import io.opentracing.Tracer;
import io.opentracing.noop.NoopTracerFactory;
import io.opentracing.util.GlobalTracer;
import lombok.extern.slf4j.Slf4j;
import lombok.val;

import javax.inject.Singleton;

/**
 * Allows for integration with Micronaut tracing annotations
 *
 * @see SpanTag
 * @see NewSpan
 * @see ContinueSpan
 */
@Slf4j
@Factory
public class DatadogTracerFactory {

    @Primary
    @Singleton
    @Requires(classes = Tracer.class, env = Environment.CLOUD)
    @SuppressWarnings("squid:S1872")
    Tracer ddTracer(final Environment environment) {
        val globalTracer = GlobalTracer.get(); // registered by dd-java-agent instrumentation (internal OTTracer implementation)
        if (environment.getActiveNames().contains(Environment.TEST)) {
            return NoopTracerFactory.create();
        }
        if (globalTracer != null && GlobalTracer.isRegistered()) {
            log.info("Registered Datadog Global Tracer bean");
            return globalTracer;
        }
        val beanInstantiationException = new BeanInstantiationException("Datadog Global Tracer not setup properly");
        log.error("Unable to create Datadog global tracer bean", beanInstantiationException);
        throw beanInstantiationException;
    }

}
```

**Comment by tylerbenson** [comment]
And what would an app without that code do with an annotated method? Does Micronaut just ignore the annotation unless a tracer is defined?

**Comment by brianwyka** [comment]
If you were to use `@NewSpan` for instance without it registered as a bean it would fall back to the `NoopTracer`.

**Comment by tylerbenson** [comment]
It's a shame it doesn't fallback to the `GlobalTracer`. That would allow this to work seamlessly. You might consider unconditionally returning `GlobalTracer.get()` in that bean registration.  No need to make it datadog specific in this case.

**Pull request closed without merging**
