### PR TITLE
Simple task scheduler

### PR DESCRIPTION
**Pull request by mcculls**
Changes:
* Renamed `CommonTaskExecutor` to `AgentTaskScheduler` to better reflect this is the agent's own task scheduler
* Simplified the scheduler to be a single thread that takes work off a `DelayQueue`
* Added support for alternative ways to clear the task target

### CODE REVIEW

**Comment by richardstartin** [comment]
Since I have encountered initialisation order problems in the past (nice to see you've removed some duct tape introduced in #1812), I think we are better off with an inversion of control model than singletons, which will lead to deterministic initialisation order. I think this would be a nice direction for this PR to take.

**Review by bantonsson — COMMENTED** [review]
Great that you untangle this!

**Comment by richardstartin** [comment]
As discussed offline, the question of deterministic initialisation is another matter and can be addressed independently of this.

**Comment by richardstartin** [comment]
Can we prioritise getting this merged?

**Review by richardstartin — APPROVED** [review]

**Review by bantonsson — APPROVED** [review]

**Review by bantonsson — APPROVED** [review]

**Review by richardstartin — APPROVED** [review]
Looks really good. Not related to this PR but I think it's probably a mistake to be using the `CommonTaskExecutor` in `DDAgentApi`. We can fix that in another PR.

**Comment by mcculls** [comment]
re. `DDAgentApi` - I replaced that use of the executor with one that always throws an exception - the intent according to the comments was to make sure we didn't accidentally trigger an async call (ie. all calls are expected to be synchronous) and also avoid starting OkHttpClient's own executor. The rejecting executor should satisfy both of those needs.

**Pull request merged**
