### PR TITLE
More general class loading instrumentation

### PR DESCRIPTION
**Pull request by trask**
Nice to be able to contribute something back!  From https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/152

### CODE REVIEW

**Comment by trask** [comment]
eeek! that's what i get for turning off `test_ibm8` on opentelemetry-auto-instr-java [to save $$](https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/129)

**Comment by trask** [comment]
@tylerbenson Oops! That was unintentional, fixed now.

**Comment by tylerbenson** [comment]
Thanks for sharing it back!

**Comment by daparthi001** [comment]
@trask 

when i am trying to get the dd-agent dd-java-agent-0.44.0.jar i am getting below error.


dd.trace 2020-03-02 16:21:33:778 +0000] [paxweb-config-1-thread-1] DEBUG datadog.trace.agent.tooling.AgentInstaller$TransformLoggingListener - Transformed org.eclipse.jetty.util.thread.QueuedThreadPool$2 -- org.ops4j.pax.web.pax-web-jetty-bundle [313]
Mar 02, 2020 4:21:33 PM org.ops4j.pax.web.service.internal.Activator updateController
SEVERE: Unable to start pax web server: datadog/trace/bootstrap/FieldBackedContextStoreAppliedMarker
java.lang.NoClassDefFoundError: datadog/trace/bootstrap/FieldBackedContextStoreAppliedMarker
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2410)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2194)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:659)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:99)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:94)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:89)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:84)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:79)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.<init>(QueuedThreadPool.java:74)
	at org.ops4j.pax.web.service.jetty.internal.JettyFactoryImpl.createServer(JettyFactoryImpl.java:88)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl$Stopped.start(ServerControllerImpl.java:448)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl.start(ServerControllerImpl.java:82)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerFactoryImpl$1.start(ServerControllerFactoryImpl.java:164)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl$Unconfigured.configure(ServerControllerImpl.java:795)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl.configure(ServerControllerImpl.java:98)
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:418)
	at org.ops4j.pax.web.service.internal.Activator.lambda$scheduleUpdateFactory$1(Activator.java:344)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: datadog.trace.bootstrap.FieldBackedContextStoreAppliedMarker not found by org.ops4j.pax.web.pax-web-jetty-bundle [313]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

Mar 02, 2020 4:21:37 PM com.sun.jmx.interceptor.DefaultMBeanServerInterceptor getAttribute
FINER: Attribute = Usage, ObjectName = java.lang:type=MemoryPool,name=PS Old Gen

**Comment by trask** [comment]
Hi @daparthi001, yeah 🙁, see fix in #1275

**Comment by daparthi001** [comment]
@trask Is this integrated in new build of java-agent ?When we will have new release ?

**Pull request merged**
