### PR TITLE
Store dbinfo in Connection context store

### PR DESCRIPTION
**Pull request by richardstartin**
Accesses to the WeakHashMap show up in profiles - this is a simple fix for a small inefficiency.
Screenshot 2020-12-16 at 21 20 05

### CODE REVIEW

**Comment by richardstartin** [comment]
this still breaks data nucleus

**Comment by mcculls** [comment]
`org.datanucleus.api.jdo.JDOConnectionJDBCImpl` will still be field-injected - if you want to exclude it from that then you'll need to add it to the `ExcludeFilter` and add an enum entry accordingly (ie. make that more general than runnable types)

You should then still be able to instrument `org.datanucleus.api.jdo.JDOConnectionJDBCImpl`, just not have it field-injected

**Comment by richardstartin** [comment]
I don't want to instrument `org.datanucleus.api.jdo.JDOConnectionJDBCImpl` since it delegates to a native connection we should be instrumenting anyway.

**Comment by richardstartin** [comment]
Unfortunately that doesn't help, and I'm not sure the improvement is worth the effort of getting to the bottom of this one.

**Review by bantonsson — APPROVED** [review]

**Review by lpriima — APPROVED** [review]

**Pull request merged**
