### PR TITLE
Bump JMXFetch to 0.49.2

### PR DESCRIPTION
**Pull request by carlosroman**
# What Does This Do

# Motivation

Bumps JMXFetch to `0.49.2` as it adds ZGC Major and Minor Cycles and ZGC Major and Minor Pauses beans support out of the box (Generational ZGC support).

# Additional Notes

Changes since last update:
* https://github.com/DataDog/jmxfetch/releases/tag/0.49.0
* https://github.com/DataDog/jmxfetch/releases/tag/0.49.1
* https://github.com/DataDog/jmxfetch/releases/tag/0.49.2

### CODE REVIEW

**Review by dougqh — APPROVED** [review]

**Review by mcculls — APPROVED** [review]

**Review by mcculls — CHANGES_REQUESTED** [review]
There are still some failing JMXFetch tests that need fixing before this can be merged

**Comment by mcculls** [comment]
FYI, the failing tests are because the JMXFetch `App` class is attempting to register an MBean in its constructor:  https://github.com/DataDog/jmxfetch/blob/0.49.1/src/main/java/org/datadog/jmxfetch/App.java#L136

When JMXFetch is embedded and the user's application is using a custom MBean manager this may fail, which is what the failing tests have detected.

Ideally JMXFetch would only attempt to register the telemetry MBean if telemetry was enabled in `AppConfig`, or perhaps when `AppConfig.isEmbedded()` is false. That would require a new release of JMXFetch, but would be the cleanest solution.

Alternatively the call to register the telemetry MBean could be moved from the `App` constructor to the `init` method (since that would also require a change to JMXFetch it would be good to still add a way to turn off registration of the telemetry MBean as discussed above.)

Without a new release of JMXFetch the two options are:
* add the updated `new-gc-default-jmx-metrics.yaml` file to `dd-java-agent/agent-jmxfetch/src/main/resources/` so it overrides the file from 0.49.0 when everything is packed into the final `dd-java-agent` jar (this is the main reason for the upgrade I believe)
  * we'll have to remember to remove this file when we next update JMXFetch, but this is a safe workaround
* Rework the way we start JMXFetch to catch failures in the constructor and retry
  * This is more risky because the construct might be setting up other resources, and since the new MBean registration is at the bottom of the constructor those resources might not be cleaned up properly if/when the registration fails

**Comment by carlosroman** [comment]
@mcculls I'll have a look and see what can be done. Happy to do a new release of JMXFetch to fix this properly.

**Comment by mcculls** [comment]
thanks @carlosroman!

**Review by mcculls — APPROVED** [review]
+1 once we have a non-snapshot version

**Review by mcculls — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
