### PR TITLE
Fix exception handling for SQL Server full mode

### PR DESCRIPTION
**Pull request by nenadnoveljic**
# What Does This Do

Finish span in the `finally` block to avoid leaks after exceptions.

# Motivation

# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [PROJ-IDENT]

### CODE REVIEW

**Review by PerfectSlayer — CHANGES_REQUESTED** [review]
Hi @nenadnoveljic 

I don't follow your changes compared to the PR description "Finish span in the finally block to avoid leaks after exceptions.". Can you elaborate a bit more but here is what I understand:

First, if there is an exception from statement closure, it will be caught and the span will still finish.
Then, you reduce the exception catch scope from `Exception` to `SQLException` so you will be catching fewer kinds of issues. It is expected?
Finally, you are no more closing the span if the `instrumentedStatement` is `null`, so you will be leaking more spans.

**Review by vandonr — APPROVED** [review]

**Comment by PerfectSlayer** [comment]
@vandonr As you approved the changes, can you help me with the concerns I raise in the comment above?

**Comment by vandonr** [comment]
> @vandonr As you approved the changes, can you help me with the concerns I raise in the comment above?

Hmm, yeah, so this PR is stemming from [this comment](https://github.com/DataDog/dd-trace-java/pull/7186#discussion_r1707600723) on a previous PR.

Actually I read the code a bit too fast without seeing your comment, but you are right, this is too high, I think we need yet another finally block a bit lower :(

**Comment by nenadnoveljic** [comment]
> Hi @nenadnoveljic
> 
> I don't follow your changes compared to the PR description "Finish span in the finally block to avoid leaks after exceptions.". Can you elaborate a bit more but here is what I understand:
> 
> First, if there is an exception from statement closure, it will be caught and the span will still finish. Then, you reduce the exception catch scope from `Exception` to `SQLException` so you will be catching fewer kinds of issues. It is expected? Finally, you are no more closing the span if the `instrumentedStatement` is `null`, so you will be leaking more spans.

Thanks for catching it. I implemented the nested exception handling now.

**Review by vandonr — APPROVED** [review]
lgtm now

**Review by PerfectSlayer — APPROVED** [review]
Thanks for the fix and the discussion about `Exception`/`Throwable`! 👍

**Pull request merged**
