### PR TITLE
Append sql comments instead of prepend to prevent exceptions on CallableStatements

### PR DESCRIPTION
**Pull request by jmeunier28**
# What Does This Do

This PR updates the logic for the APM-DBM link feature introduced in https://github.com/DataDog/dd-trace-java/pull/4847. It changes from prepending the sql comments, containing the APM trace context, to appending them to the raw sql. This requires no changes on the DBM side of things in either the agent or our backend.

Jira ticket: [DBMON-2759](https://datadoghq.atlassian.net/browse/DBMON-2759)

# Motivation

This fixes an issue, which has been reported by several customers that executing `CallableStatement`s with the following syntax causes exceptions to be thrown when enabling APM-DBM link:

> The customer’s code base makes a CallableStatement statementvariable = connection.prepareCall("{call some_function_namehere(?,?,?) }";) and whenever both of these are active, the Java application starts throwing syntax error at or near "{" over and over.

We were able to reproduce this, using the latest version of the java tracer && an internal application. It seems to be caused by the SQL comments we inject being _prepended_ instead of _appended_.  For example, the issue of prepending the comment was reproduced with a simple java application (without APM-DBM link enabled), which did the following:

```java
  final String storedProcedureCall = "/*test commnet*/ {call foo(?, ?)}";
  CallableStatement callableStmt = con.prepareCall(storedProcedureCall);
  callableStmt.setInt(1,10);
  callableStmt.setInt(2,11);
  callableStmt.execute();
  callableStmt.close(); 
```

... this throws the same exception with message `Incorrect syntax near '{'.`

# Proof of Fix

After doing a custom build of this tracer code, we deployed our test app, which runs a combination of `PreparedStatement`/`Statements`/`CallableStatement` & no longer saw the `Incorrect syntax near '{'.` exception being thrown. 

We were also able to confirm that injection is still working properly, e.g: our events are being properly decorated:

Screen Shot 2023-10-12 at 5 26 06 PM

Screen Shot 2023-10-12 at 5 26 15 PM

# Expected DBM Behavior for Stored Procedures

Stored Procedures aren't supported for the APM-DBM usecase (unless the same app that is calling them is the thing that created the stored procedure & the linking was enabled). Otherwise, we wouldn't see the comments if someone had code that was simply calling `EXEC proc` or `{call proc}`, since the actual text we see in the activity code is either:

1. The entire stored proc text e.g.:
```tsql
CREATE PROCEDURE foo
BEGIN
-- do stuff
END;
```
2. The [currently executing query](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/activity.py#L55-L60) in the context of the stored proc

Neither, contains the text `EXEC proc`, which is what would have the comment injected via the tracer.

Obviously, this is of secondary concern here. Updating the tracer to append the comment will fix this edge case being reported by customers. **We really don't want the feature to cause users to see exceptions being thrown in their production code.**

[DBMON-2759]: https://datadoghq.atlassian.net/browse/DBMON-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jmeunier28** [comment]
Looks like the tests failures aren't related to my PR?
```
* What went wrong:
Execution failed for task ':dd-java-agent:instrumentation:grizzly-http-2.3.20:test'.
> There were failing tests. See the report at: file:///home/circleci/dd-trace-java/workspace/dd-java-agent/instrumentation/grizzly-http-2.3.20/build/reports/tests/test/index.html
```

... although I'm not sure why this is failing now:
```
self = <test_db_integrations_sql.Test_Agent_Mssql_db_integration object at 0x7f05030259d0>

    def test_obfuscate_query(self):
        """ All queries come out obfuscated from agent """
        for db_operation, request in self.requests[self.db_service].items():
            span = self._get_sql_span_for_request(request)
            # We launch all queries with two parameters (from weblog)
            if db_operation == "insert":
                expected_obfuscation_count = 1
            elif db_operation == "procedure":
                # Insert and procedure:These operations also receive two parameters, but are obfuscated as only one.
                # Nodejs: The proccedure has a input parameter, but we are calling through method `execute`` and we can't see the parameters in the traces
                expected_obfuscation_count = 0 if context.library.library == "nodejs" else 2
            else:
                expected_obfuscation_count = 2
    
>           observed_obfuscation_count = span["meta"]["sql.query"].count("?")
E           TypeError: 'NoneType' object is not subscriptable

tests/integrations/test_db_integrations_sql.py:556: TypeError
```
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/30177/workflows/06d05af0-63ff-41e8-809e-a2c72d369297/jobs/1022674

**Review by justiniso — APPROVED** [review]

**Review by ygree — CHANGES_REQUESTED** [review]
Looks good! Except for `integrations-core`. If it wasn't updated on purpose then follow https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#git-submodule-setup to exclude it from the change.

**Comment by jmeunier28** [comment]
> Looks good! Except for integrations-core. If it wasn't updated on purpose then follow https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#git-submodule-setup to exclude it from the change.

@ygree  ah okay, I ran `git config --local submodule.recurse true` and then rebase on master, is this correct?

**Comment by PerfectSlayer** [comment]
Looks like `integration-core` is still in your changeset.
Try `git submodule update` to update it and commit it.
You can then squash your 3 commits together and force push it to your PR branch.

**Review by ygree — APPROVED** [review]
Looks good to me!

**Pull request merged**
