### PR TITLE
Minimize size of final JAR

### PR DESCRIPTION
**Pull request by cataphract**
( Built on top of https://github.com/DataDog/dd-trace-java/pull/2664 )

Size difference is 1.35 MB:

```
glopes ~/repos/dd-trace-java (master *+%>) $ gradle --no-daemon clean dd-java-agent:shadowJar
...
BUILD SUCCESSFUL in 36s
546 actionable tasks: 545 executed, 1 up-to-date
glopes ~/repos/dd-trace-java (master *+%>) $ ls -l dd-java-agent/build/libs/dd-java-agent-0.79.0-SNAPSHOT.jar 
-rw-rw-r-- 1 glopes glopes 12094832 mai  5 19:18 dd-java-agent/build/libs/dd-java-agent-0.79.0-SNAPSHOT.jar

glopes ~/repos/dd-trace-java (master *+%>) $ git stash
Saved working directory and index state WIP on master: 65ef5eb7a Fix :dd-java-agent:shadowJar build with config on demand
glopes ~/repos/dd-trace-java (master %>) $ gradle --no-daemon clean dd-java-agent:shadowJar
...
BUILD SUCCESSFUL in 35s
542 actionable tasks: 541 executed, 1 up-to-date
glopes ~/repos/dd-trace-java (master %>) $ ls -l dd-java-agent/build/libs/dd-java-agent-0.79.0-SNAPSHOT.jar 
-rw-rw-r-- 1 glopes glopes 13510830 mai  5 19:20 dd-java-agent/build/libs/dd-java-agent-0.79.0-SNAPSHOT.jar
```

Diff of classes [in this gist](https://gist.github.com/cataphract/a41ed1c05e126f3b360b703562edd72b).

The owasp.encoder library was completely eliminated. IIRC, only dependent was `org.openjdk.jmc.common.util.XmlToolkit`, which is unused.

### CODE REVIEW

**Comment by devinsba** [comment]
Any idea why this part of the diff happened:
```
-inst/java/
-inst/java/util/
-inst/java/util/concurrent/
-inst/java/util/concurrent/CompletableFutureAdvice.classdata
-inst/java/util/concurrent/CompletableFutureAdvice$UniConstructor.classdata
-inst/java/util/concurrent/CompletableFutureAdvice$UniSubTryFire.classdata
```

**Comment by cataphract** [comment]
> Any idea why this part of the diff happened:
> 
> ```
> -inst/java/
> -inst/java/util/
> -inst/java/util/concurrent/
> -inst/java/util/concurrent/CompletableFutureAdvice.classdata
> -inst/java/util/concurrent/CompletableFutureAdvice$UniConstructor.classdata
> -inst/java/util/concurrent/CompletableFutureAdvice$UniSubTryFire.classdata
> ```

Thanks, I'd missed this one. This is implemented as postprocessing step on the shadow jar, so by this time information about the location of the classes is lost, which is unfortunate. I implemented the filter as eliminating all the classes that are not (transitively) reachable from classes starting with datadog or com.datadog/com.datadoghq, but that obviously misses this case.

**Comment by devinsba** [comment]
Cool, if you rebase on master I think we can merge this directly given approval

**Review by richardstartin — APPROVED** [review]
Nice : 👍

**Comment by richardstartin** [comment]
Where have the CI checks gone?

**Comment by tylerbenson** [comment]
@richardstartin the CI checks aren't required here because the base is another branch, not master.  Unfortunately CircleCI doesn't seem to be triggering on @cataphract's PRs and I suggested he contact their support.

**Review by richardstartin — APPROVED** [review]

**Review by mcculls — CHANGES_REQUESTED** [review]
In addition to the `CompletableFutureAdvice` it also currently removes:
```
inst/org/glassfish/jersey/client/WrappingResponseCallbackAdvice.classdata
```
There will likely be other integrations in the future where we need to access package-private types, causing the advice or helpers to be located in non-datadog packages.

So we'll need some way to tell the minimizer to always keep instrumentation advice/helpers regardless of their package (basically keep everything that is compiled in our build.)

**Comment by richardstartin** [comment]
I think we really need to see the tests run for this to iron out some of the little issues

**Comment by cataphract** [comment]
I've addressed the advice problem, and also minimized the metrics jar and the shared jar. The new final size is 10953781 bytes, 2.6 MB less.

The final code is not very pretty, with shared jar minimization working differently than the rest, but I couldn't come up with an artful way of unifying the two strategies.

**Comment by mcculls** [comment]
FYI, looks like `net.jpountz.lz4.LZ4JavaSafeCompressor` is being removed but is actually needed for profile uploading:
```
[dd.trace 2021-05-06 22:10:37:299 +0000] [OkHttp http://localhost:54237/...] DEBUG com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile to http://localhost:54237/
java.io.IOException: java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor
	at com.datadog.profiling.uploader.CompressingRequestBody.writeTo(CompressingRequestBody.java:198)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:25)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor
	at net.jpountz.lz4.LZ4Factory.instance(LZ4Factory.java:53)
	at net.jpountz.lz4.LZ4Factory.safeInstance(LZ4Factory.java:105)
	at net.jpountz.lz4.LZ4Factory.fastestJavaInstance(LZ4Factory.java:141)
	at net.jpountz.lz4.LZ4Factory.fastestInstance(LZ4Factory.java:169)
	at net.jpountz.lz4.LZ4FrameOutputStream.<init>(LZ4FrameOutputStream.java:115)
	at net.jpountz.lz4.LZ4FrameOutputStream.<init>(LZ4FrameOutputStream.java:102)
	at com.datadog.profiling.uploader.CompressingRequestBody.toLz4Stream(CompressingRequestBody.java:339)
	at com.datadog.profiling.uploader.CompressingRequestBody.attemptWrite(CompressingRequestBody.java:227)
	at com.datadog.profiling.uploader.CompressingRequestBody.writeTo(CompressingRequestBody.java:167)
	... 22 more
Caused by: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at datadog.trace.bootstrap.DatadogClassLoader$DelegateClassLoader.loadClass(DatadogClassLoader.java:191)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.jpountz.lz4.LZ4Factory.classInstance(LZ4Factory.java:177)
	at net.jpountz.lz4.LZ4Factory.<init>(LZ4Factory.java:191)
	at net.jpountz.lz4.LZ4Factory.instance(LZ4Factory.java:51)
	... 30 more
```

**Comment by mcculls** [comment]
Unfortunately the way lz4 dynamically builds the implementation name makes this use hard to spot via bytecode analysis:

https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/lz4/LZ4Factory.java#L196

**Comment by cataphract** [comment]
Tests are now passing.

**Review by bantonsson — APPROVED** [review]
👍 File diff looks good as far as I can tell.

**Review by richardstartin — APPROVED** [review]

**Review by mcculls — COMMENTED** [review]
Yes, diff looks ok now -thanks

**Comment by mcculls** [comment]
These are the JNR/JFFI types which are loaded from master when testing misconfigured Unix Domain Sockets on OSX which aren't being loaded in the minimize branch:
```
com.kenai.jffi.Version
com.kenai.jffi.internal.StubLoader
com.kenai.jffi.internal.StubLoader$1
com.kenai.jffi.internal.StubLoader$CPU
com.kenai.jffi.internal.StubLoader$OS

jnr.constants.platform.darwin.Errno
jnr.constants.platform.darwin.Errno$StringTable
jnr.constants.platform.darwin.ProtocolFamily
jnr.constants.platform.darwin.Shutdown
jnr.constants.platform.darwin.Sock
jnr.constants.platform.darwin.SocketLevel
jnr.constants.platform.darwin.SocketOption

jnr.ffi.provider.jffi.Provider
jnr.ffi.provider.jffi.platform.x86_64.darwin.TypeAliases
```

Excluding types from minimize by names could be fragile in this case - it would be easy to miss OS specific types for platforms that we don't test on. Maybe it would be safer to exclude whole libraries from minimize where we know they use a lot of reflection to load types based on the environment?

**Comment by mcculls** [comment]
Confirmed that Unix Domain Sockets (UDS) won't work properly without those types - so this also affects properly configured tracers that use UDS, not just the misconfigured case.

**Comment by richardstartin** [comment]
Just another note - we're already down to 12.5MB from 12.9MB just by losing the JMC dependency, so this change is now only worth 1.1MB for the risk of anything else like Stuart found.

**Comment by mcculls** [comment]
This effort has been very useful in showing that the number of unused classes in the tracer isn't too bad at the moment. (This wasn't always the case - previously we were using Guava which would have really benefited from this minimization.)

That said, I think the benefit of minimization is currently outweighed by the risk that it could remove classes that are in fact needed at runtime. This sort of issue can be hard to diagnose remotely, so IMHO I don't think this is something we should merge right now.

We may revisit this if we ever need to add a large dependency where we only use a small subset of features - in that case I think it would be better to explicitly list the jars/packages to be minimised, rather than attempt to minimize everything. That would allow us to selectively target known areas of bloat which are amenable to minimization.

**Pull request closed without merging**
