### PR TITLE
graphql: Set resource name to operation name (or query when anonymous) to make…

### PR DESCRIPTION
**Pull request by theJC**
… Datadog resource view extremely useful for GraphQL requests

# What Does This Do
Resolves: https://github.com/DataDog/dd-trace-java/issues/4210
https://help.datadoghq.com/hc/en-us/requests/1003318

# Motivation
Having much richer and useful Datadog Resource View for graphql requests.  Performance characteristics vary widely across operations, but are much more likely to similar and SLOs will likely be aligned based on the operation being executed.

https://www.apollographql.com/docs/react/data/operation-best-practices/#name-all-operations

Platforms like Apollo Studio leverage operation names to group and measure performance using operation-level metrics.

# Additional Notes

### CODE REVIEW

**Comment by theJC** [comment]
@ygree  -- I believe this is the last one on our list of issues that would allow us to migrate off our custom libraries and just use Datadog instrumentation out of the box.  This is very similar in nature to https://github.com/DataDog/dd-trace-java/pull/4663, only from an graphql execution perspective rather than field perspective.

If you can help us get this reviewed and merged, it would be appreciated (and as an added bonus, I'll leave you alone for a while ;) ) Thanks!

**Review by ygree — APPROVED** [review]
Looks good! Thank you for this contribution!

**Comment by bantonsson** [comment]
@ygree @theJC this has started failing some tests intermittently as can be seen here https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/23372/workflows/34d367e4-93bf-49c0-ab54-ddb727e0e0c5/jobs/676542

**Comment by theJC** [comment]
https://github.com/DataDog/dd-trace-java/pull/5008 created to address issue with unit tests due to timing of merges and new unit test from one pull request not coded to expect new behavior from the other pull request.

**Pull request merged**
