### PR TITLE
Monitoring counters expect statsd to exist

### PR DESCRIPTION
**Pull request by mar-kolya**
So use noop statsd client like we do in other places

### CODE REVIEW

**Comment by richardstartin** [comment]
This is an oversight. Thanks for the PR. I would prefer to address this with a dummy disabled counter implementation which does nothing.

**Comment by mar-kolya** [comment]
🤷 I'm not sure... `CoreTracer` uses noop statsd specifically for the reason to avoid dealing with nulls everywhere... but up to you...

**Comment by richardstartin** [comment]
OK. But it should do _nothing_ if monitoring is disabled. Thanks for drawing this to my attention, I'm about to submit a PR (with lots of tests).

**Comment by mar-kolya** [comment]
sure, anytime.

**Review by tylerbenson — APPROVED** [review]

**Review by richardstartin — APPROVED** [review]
We can merge this and apply #1881 on top of it

**Comment by richardstartin** [comment]
@mar-kolya can you merge so I can rebase please?

**Comment by mar-kolya** [comment]
sure, thanks!

**Comment by dougqh** [comment]
Yes, the desire to truly nothing is why I had a NullMonitor on the LogWriter at first rather than just using a NoOpStatsdClient.

**Pull request merged**
