### PR TITLE
Reduce overhead of URLAsResourceName decorator

### PR DESCRIPTION
**Pull request by tylerbenson**
Using `new URL()` just to parse the path out was rather expensive.  This should improve the situation.

### CODE REVIEW

**Comment by jbachorik** [comment]
Can you attach the pre and post change  benchmark results to PR?

**Comment by dougqh** [comment]
Yes, this is place where a JMH benchmark should work really well.  And should be easy to write -- even if we cannot tie into the build system yet.

**Comment by tylerbenson** [comment]
Here are the results from the benchmark I ran while developing this:

```
Benchmark                                          Mode  Cnt     Score   Error   Units
URLAsResourceNameBenchmark.testFullUrl            thrpt          0.846          ops/us
URLAsResourceNameBenchmark.testFullUrlOptimized   thrpt          1.657          ops/us
URLAsResourceNameBenchmark.testPathOnly           thrpt          0.352          ops/us
URLAsResourceNameBenchmark.testPathOnlyOptimized  thrpt          1.509          ops/us
URLAsResourceNameBenchmark.testFullUrl             avgt          1.027           us/op
URLAsResourceNameBenchmark.testFullUrlOptimized    avgt          0.612           us/op
URLAsResourceNameBenchmark.testPathOnly            avgt          2.336           us/op
URLAsResourceNameBenchmark.testPathOnlyOptimized   avgt          0.542           us/op
URLAsResourceNameBenchmark.testFullUrl               ss         68.989           us/op
URLAsResourceNameBenchmark.testFullUrlOptimized      ss         51.074           us/op
URLAsResourceNameBenchmark.testPathOnly              ss       1108.589           us/op
URLAsResourceNameBenchmark.testPathOnlyOptimized     ss         53.475           us/op
```

Note: I didn't have the iterations set very high (see config from the PR), so there's likely a larger margin of error, but I think it's enough to demonstrate the improvement.

One reason for the significant improvement on the "path-only" test is because URL throws an exception internally if there isn't a protocol defined.

Another point... I think URL also has some synchronized method usage internally that would have resulted in greater difference between the optimized version if the test had more concurrency.

**Comment by dougqh** [comment]
Overall, I'd say the benchmark results are pretty convincing.

With any microbenchmark, I'm sure there's high variation.  However, I expect the old approach had a higher variation, since it probably did more allocation.

**Pull request merged**
