### PR TITLE
Update misc versions.

### PR DESCRIPTION
**Pull request by tylerbenson**
Lombok to 1.8.4
Byte Buddy to 1.9.5

Test dependencies:
Test-sets plugin to 2.0.2
System-rules to 1.19.0

### CODE REVIEW

**Comment by tylerbenson** [comment]
Looks like I broke something in here.  I'll look into it tomorrow.

**Comment by realark** [comment]
Let's hold off on merging this until after the 0.19 release.

**Comment by tylerbenson** [comment]
@realark look at you being all conservative 😉

Looks like it was the test-set 2.0.2 plugin that was problematic.  I switched it back to a more minor upgrade.

**Comment by realark** [comment]
0.19 is out so this is good to go. Thanks for your patience

**Pull request merged**
