### PR TITLE
metrics updates

### PR DESCRIPTION
**Pull request by richardstartin**
* Add fields to uniquely identify payloads
* Target v0.6/stats endpoint as v0.5/stats has been retired
* Adjust relative accuracy to match format used elsewhere

### CODE REVIEW

**Review by bantonsson — APPROVED** [review]

**Review by charliegracie — APPROVED** [review]

**Review by tylerbenson — APPROVED** [review]
I assume the potential impacts to metric cardinality has already been considered.

**Comment by richardstartin** [comment]
>I assume the potential impacts to metric cardinality has already been considered.
@tylerbenson there is no impact on metric cardinality. These are just fields which can be used to detect redelivery. They don't need to be part of an aggregation key.

**Comment by tylerbenson** [comment]
Ok, I didn't understand that.  It seemed like it was being added as a tag.  (I don't quite understand the difference between a field and a tag.)
In that case 👍

**Comment by richardstartin** [comment]
There's no difference between a field and a tag, but the effect on cardinality is a question of whether the information added to the payload will be included in the aggregation key, which these won't.

**Comment by richardstartin** [comment]
https://github.com/DataDog/datadog-agent/pull/7832 changed the endpoint name so it's updated here

**Pull request merged**
