### PR TITLE
avoid converting binary document to tree when possible on later mongo driver versions

### PR DESCRIPTION
**Pull request by richardstartin**
Newer mongo driver versions allow more efficient reading of BSON documents. Unfortunately this isn't possible on older driver versions, so I added some instrumentation to extract the document's buffer and do the same thing manually.

### CODE REVIEW

**Review by bantonsson — APPROVED** [review]

**Comment by richardstartin** [comment]
@bantonsson yes, and the majority of them (in my experience with this driver) tend to be the ones we'll instrument (the ones sent to and from the database) which have alignment shadow to absorb the field. The problem is that for the document type where this adds eight bytes, what you're offsetting it against also contains `BsonDocument`s... It's possible this will cause small problems with mapping frameworks using a little more memory.

**Review by tylerbenson — APPROVED** [review]

**Comment by tylerbenson** [comment]
If this api is only available in newer versions, why didn't muzzle require an updated version range?

**Comment by richardstartin** [comment]
> If this api is only available in newer versions, why didn't muzzle require an updated version range?

@tylerbenson the API is available in v4 of the driver (we have two mongo instrumentation modules)

**Comment by tylerbenson** [comment]
Ok. I was confused what you were referring to since you made changes to both 3.x and 4.x modules. 
Now I understand better though. You're taking advantage of the new API in 4.x and adding instrumentation to expose similar behavior to 3.x since it doesn't have the needed API.
👍

**Comment by richardstartin** [comment]
Yes the changes were made in separate commits

**Pull request merged**
