### PR TITLE
remove java 7 test

### PR DESCRIPTION
**Pull request by richardstartin**
# What Does This Do

this is failing on another branch

# Motivation

# Additional Notes

### CODE REVIEW

**Comment by mcculls** [comment]
Wasn't this added to make sure we got a clear message when anyone tried to use v1.x of the tracer on Java 7?

Which branch is this failing on?  I'd like to see if the test or its config needs fixing rather than drop the test completely.

**Comment by richardstartin** [comment]
> Wasn't this added to make sure we got a clear message when anyone tried to use v1.x of the tracer on Java 7?
> 
> Which branch is this failing on? I'd like to see if the test or its config needs fixing rather than drop the test completely.

I have no idea why it was added :) 

It's failing here on #3974: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/19342/workflows/3137095e-271c-46b4-8312-bf28f15bcd64/jobs/490044

**Comment by richardstartin** [comment]
The failure may be transient because of the recent release

**Comment by mcculls** [comment]
Yes, 1.2.0 is staged but hasn't been pushed to central yet - once that's done the test should pass (but it does show the test needs improving to handle this state)

**Pull request closed without merging**
