### PR TITLE
Support field-injection of record classes

### PR DESCRIPTION
**Pull request by mcculls**

### CODE REVIEW

**Review by amarziali — APPROVED** [review]
thank you

**Review by PerfectSlayer — COMMENTED** [review]
Dumb question: what's preventing us to migrate all ASM version to 9?

**Comment by mcculls** [comment]
Use of the `ASM9` API version only unlocks use of `PermittedSubclasses` which isn't required by field-injection.

Previously we've kept the API version at the level that we use/need - we could bump everything to the latest API level and it shouldn't make much difference, but for this specific PR I wanted to just do a small increment.

**Comment by PerfectSlayer** [comment]
> But you could create a PR to introduce a new shared constant representing the embedded API version (currently 9) and use that everywhere...

That was one of my thoughts as we end up using different values across the code base.

**Pull request merged**
