### PR TITLE
Add instrumentation to propagate across scala and java promises properly

### PR DESCRIPTION
**Pull request by bantonsson**
Promise test for `CompletableFuture`.

### CODE REVIEW

**Comment by richardstartin** [comment]
Will this test pass or is it demonstrating an issue?

**Comment by bantonsson** [comment]
It doesn't pass on my machine. It's hopefully demonstrating the difference in behavior that we will have between `scala` and `java`.

**Comment by bantonsson** [comment]
@tylerbenson Thanks for the instrumentation. I'll keep adding some more tests and fixes for different executors.

**Comment by bantonsson** [comment]
The quest continues in #1933

**Pull request closed without merging**
