### PR TITLE
Remove Hystrix test retry and timeout

### PR DESCRIPTION
**Pull request by bantonsson**

### CODE REVIEW

**Comment by richardstartin** [comment]
What's the motivation? #2389 removes the scope leak which prevents this test from passing in strict mode, but either uncovers or causes more problems.

**Comment by bantonsson** [comment]
So the motivation is that all the failures that I have seen is a timeout on this form:
```
Method timed out after 5.00 seconds
        at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8383)
        ...
        at HystrixObservableChainTest$__spock_feature_2_0_closure2.closure5$_closure10(HystrixObservableChainTest.groovy:137)
        at datadog.trace.agent.test.asserts.SpanAssert.assertSpan(SpanAssert.groovy:37)
        ...
```
The test is obviously in the middle of verifying the results via `assertTrace/assertSpan` but it's too slow and times out within the 5 second range (probably for the 3rd time). I think that having the `@Retry` annotation on any test, except maybe as a port conflict mitigation (until that is solved properly), is just plain wrong.

I'm going to rerun this whole PR on CI for a number of times and see if it fails.

**Comment by bantonsson** [comment]
I have now run the whole build for all platforms (rerun from start) 13 times without this test failing once.

**Review by devinsba — APPROVED** [review]

**Review by richardstartin — APPROVED** [review]
I'll rebase on this because I had an improvement to make the test run in strict mode

**Pull request merged**
