### PR TITLE
Move nested helper classes to top level, add smoke test for ApacheHttpClient classloader isolation

### PR DESCRIPTION
**Pull request by richardstartin**
Because some of `ApacheHttpClientInstrumentation`'s helper classes, which are visible to the application classloader are nested, but their enclosing class `ApacheHttpClientInstrumentation` is not made visible to the target classloader, calling `Class.getSimpleName` throws `NoClassDefFoundError`

```java
  @Override
  public String[] helperClassNames() {
    return new String[] {
      packageName + ".ApacheHttpClientDecorator",
      packageName + ".HttpHeadersInjectAdapter",
      packageName + ".HostAndRequestAsHttpUriRequest",
      getClass().getName() + "$HelperMethods",
      getClass().getName() + "$WrappingStatusSettingResponseHandler",
    };
  }
```

### CODE REVIEW

**Review by devinsba — APPROVED** [review]
Are there more places we use this pattern that we should clean up?

**Comment by richardstartin** [comment]
@devinsba be my guest 👍🏻

**Comment by richardstartin** [comment]
This actually doesn't have to be an agent to cause this, it could be any application which does any kind of classpath scan and needs to load the enclosing class.

**Comment by richardstartin** [comment]
I've done all beginning with letter A.

**Review by lpriima — APPROVED** [review]

**Comment by dougqh** [comment]
Long term, I think I'd like us to draw a firm line between the instrumentation and the parts that are actually injected (helper class + advice class).  My usual way of doing that is by separating into separate source folders & build units.

My main reason for this is that I want the runtime separation to be obvious in the source.  Unfortunately, I think the current nesting skews in the other direction of making the runtime separation non-obvious which leads to surprising problems like this.

**Pull request merged**
