### PR TITLE
Fix async propagation in some versions of undertow

### PR DESCRIPTION
**Pull request by cataphract**
The executor that netty uses in more recent versions is not instrumented.

### CODE REVIEW

**Review by mcculls — APPROVED** [review]

**Comment by richardstartin** [comment]
I think this will cause issues: this executor wraps the runnable to preserve the classloader:

```java
final Runnable realRunnable = JBossExecutors.classLoaderPreservingTaskUnchecked(runnable);
```

And this instrumentation will wrap the runnable in a bootstrap type (FutureTask), which breaks this classloader preservation. The wrapper type `ContextClassLoaderSavingRunnable` is already instrumented to activate its embedded continuation, so what about instrumenting its constructor to capture an active scope, or capture on exit from `BossExecutors.classLoaderPreservingTaskUnchecked(Runnable)` instead?

**Comment by richardstartin** [comment]
The title and label are also misleading because this isn't part of netty but belongs to jboss-threads.

**Comment by cataphract** [comment]
> I think this will cause issues: this executor wraps the runnable to preserve the classloader:
> 
> ```java
> final Runnable realRunnable = JBossExecutors.classLoaderPreservingTaskUnchecked(runnable);
> ```
> 
> And this instrumentation will wrap the runnable in a bootstrap type (FutureTask), which breaks this classloader preservation. The wrapper type `ContextClassLoaderSavingRunnable` is already instrumented to activate its embedded continuation, so what about instrumenting its constructor to capture an active scope, or capture on exit from `BossExecutors.classLoaderPreservingTaskUnchecked(Runnable)` instead?

Is the concern here that we might ourselves use or alter the context classloader? Because all I can see it does is save the context classloader at the time the `Runnable` is submitted and restore it for the duration of the execution of the `Runnable`. As long as we don't ourselves modify the context classloader, it shouldn't matter whether we execute our code around the "preserving" runnable (in the wrapper we're adding) or inside it.

**Comment by richardstartin** [comment]
Apologies - the implementation of the wrapping method indeed does not depend on the type of the runnable, so this fix is fine. I'd just make the description and labels refer to quarkus instead of netty though.

**Comment by cataphract** [comment]
> I'd just make the description and labels refer to quarkus instead of netty though.

Right I got confused. This causes problems in undertow, not netty.

**Pull request merged**
