### PR TITLE
Workaround shutdown bug on IBM JDK 8 sr6fp15…

### PR DESCRIPTION
**Pull request by mcculls**
…where destroying a forked `java.lang.Process` can leave it hanging

### CODE REVIEW

**Comment by richardstartin** [comment]
I'm ok with waiting for a fixed image for IBM8

**Comment by mcculls** [comment]
@richardstartin I still think it's useful - makes it easier to spot other issues with the IBM8 tests while waiting for the JDK fix

**Review by bantonsson — APPROVED** [review]
I think this is good and will make us notice other bad behavior in forked processes.

**Review by richardstartin — APPROVED** [review]
fair enough

**Review by devinsba — APPROVED** [review]
Maybe these lines should print to stderr but makes sense to me

**Review by tylerbenson — APPROVED** [review]

**Pull request merged**
