### PR TITLE
Add instrumentation for jetty 11

### PR DESCRIPTION
**Pull request by pdenis1**
Adds support for jetty 11, which imports jakarta.ws.rs rather than javax.ws.rs.  

Also, there is a change in the method signature of org.eclipse.jetty.server.handler.ContextHandler$Context#setContext.  It now takes a Context as well as a String parameter, so this PR also fixes that instrumentation.

```
named("setContext")
            .and(takesArgument(0, named("org.eclipse.jetty.server.handler.ContextHandler$Context")))
            .and(takesArgument(1, String.class)),
        RequestInstrumentation.class.getName() + "$SetContextPathAdvice");
```

### CODE REVIEW

**Comment by bantonsson** [comment]
Hi @pdenis1 and thanks for the contribution. The Jetty 11 code is Java 11+ only, but the whole build runs on Java 8 (for Java 7 support), so it needs to have separate source directories for the Java 11 parts. I've split up the build and the code, and opened a PR against your original branch here PasonSystems/dd-trace-java#2

It would be great if some tests could be added as well.

**Comment by pdenis1** [comment]
@bantonsson Thanks for your help with the project structure!  I've added tests that are passing locally but when I pushed to CircleCI, the build is failing due to jakarta.servlet.ServletException class format (which is java 11).  Any advice?  Do I need to rename the src/test/groovy folder to src/test/groovy11?

**Comment by bantonsson** [comment]
@pdenis1 Not really sure yet. I'll take a look at why the compilation fails.

**Comment by pdenis1** [comment]
No worries, @bantonsson!  Once again, tyvm for your MR to fix!  The build is passing now.

**Review by devinsba — APPROVED** [review]

**Review by bantonsson — APPROVED** [review]

**Comment by pdenis1** [comment]
@bantonsson you guys work as late as i do, apparently!

**Comment by bantonsson** [comment]
Hey @pdenis1, I'm based in Sweden. It's 9:20 in the morning 😉

**Comment by bantonsson** [comment]
Thanks once again @pdenis1 for contributing. We hope to make it a way smoother experience.

**Comment by pdenis1** [comment]
no thank you!  ❤️

**Pull request merged**
