### PR TITLE
Consistently use '[,]' to denote 'all versions' in muzzle…

### PR DESCRIPTION
**Pull request by mcculls**
… and don't use assertInverse because it doesn't make sense for 'all versions'

### CODE REVIEW

**Comment by richardstartin** [comment]
This still looks weird to me. Is there some precedent for this notation? What I read is "a range with closed _but undefined_ lower and upper bounds".

**Comment by mcculls** [comment]
@richardstartin muzzle uses Maven's dependency resolver to find the artifacts within the range. Maven version ranges were originally documented [here](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges) - since then there's been some evolution around treatment of snapshots and common 'prerelease' qualifiers, but the notation still doesn't let you use single wildcards like `+` or `*`.

A version range in Maven has to be surrounded by brackets, otherwise it is parsed as a single version. This means we either have to use `(,)` or `[,]` to denote all versions - ie. specify a range but don't provide any upper or lower bound. Out of those two options `[,]` is arguably closer to the intent.

**Comment by richardstartin** [comment]
@mcculls that link doesn't define or describe expressions like `(,)` or `[,]`

**Comment by richardstartin** [comment]
Ignore the complaints about the notation. If `[,]` or `(,)` is accepted to mean "all versions" by other systems, then I don't think it's productive to debate flaws in the notation, but I also don't see any gain from this PR. We're just passing the notation through to another system, so attempts to restrict ourselves to a subset of that notation feels vain.

**Comment by mcculls** [comment]
@richardstartin that's because in Maven you don't typically declare a dependency to "all versions" - so the design doc shows examples of ranges used in practice. That's where the version range syntax originated and that's what the code implemented. Fundamentally you need to use the boundary characters otherwise it won't treat it as a range:

https://github.com/apache/maven-resolver/blob/master/maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionScheme.java#L115

So we have the following choices:
* `(,)` - which already confused a number of people and which is only used in a few places in our codebase
* `[,]` - the alternative approach used by the majority of instrumentations declaring they work with all versions
* `[,)` - not used anywhere yet
* `[0,)` - not used anywhere yet

My main concerns are that a) we're consistent and b) we avoid using `assertInverse` for all versions because that makes no sense. Given that the majority of instrumentations have already self-selected `[,]` then that would be the pragmatic choice to standardize on, but `[,)` is also OK if the team as a whole prefers that. The Maven code doesn't care because in both cases there's no restriction and the therefore the actual character doesn't have any effect because there's nothing to cap.

**Comment by richardstartin** [comment]
The consistency introduced by this PR is unenforceable and is based on an arbitrary choice, which makes future divergence likely. I find `[,]` every bit as confusing as `(,)` (this is the drawback of mimicking well-defined notations). I think we are better off accepting that there's been a short discussion about maven version syntax as we're using it in muzzle directives, and that `(,)` and `[,]` are pathological instances of the notation which happen to mean the same thing.

**Comment by mcculls** [comment]
This PR also removes `assertInverse` from places where we declare 'all versions' as that doesn't make sense and causes confusion. At the same time as removing those it was trivial to clean up the 'all versions' ranges, and I don't want to spend more time pulling these apart. Since this really is a simple change I don't see why we can't merge it as-is.

**Comment by richardstartin** [comment]
I don't think it does "clean up the 'all versions' ranges" - it _changes_ them from one form accepted by a system we don't control, to another form accepted by a system we don't control. What happens if somebody contributes a new instrumentation and uses the forbidden (but valid) form of "all ranges" - do we request changes in the code review or do we accept the inconsistency? I'm wary of manually enforced conventions because it creates "in groups" (i.e. those in the know) - so I oppose introducing one unless a linter is introduced with the change.

**Comment by mcculls** [comment]
I'm going to leave this PR open with the intent to merge it - it's only a small change and doesn't break anything

**Comment by richardstartin** [comment]
OK. My view is that if it's important enough to standardise, then it's worth the time to introduce an enforcing linter. The perceived inconsistency here must not be grounds for requesting changes in the future.

**Review by tylerbenson — APPROVED** [review]
Thanks for the cleanup.

**Review by randomanderson — APPROVED** [review]

**Pull request merged**
