### PR TITLE
Fix akka-http instrumentation.

### PR DESCRIPTION
**Pull request by dpratt**
Remove compiled Scala artifacts from the actual instrumentation. Scala
is not binary compatible across major versions, and having
AkkaHttpClientTransformFlow.scala be in the artifact causes problems
when using anything but Scala 2.11.

Having the AkkaHttpClientTransformFlow implementation be in pure java
utilizing the Akka-stream Java DSL ensures that this will work across
any given Scala major version.

### CODE REVIEW

**Comment by dpratt** [comment]
I'm not entirely sure why the unit tests and the muzzle plugin are failing - it's almost like the test HTTP server isn't being started.

Can somebody on the maintainer team point me in the right direction?

**Comment by dpratt** [comment]
After more investigation, I'm convinced that it's due to the SuperPool instrumentation.

In fact, it's likely that this instrumentation never really worked in the first place, since SuperPools explicitly do not respect ordering of requests and responses. This PR kills two birds with one stone - it fixes some Scala binary compatibility versions w.r.t. the instrumentation, and removes the non-functional instrumentation that was likely generating nonsense/incorrect spans for anybody that was using it.

For more info on SuperPool ordering, see https://doc.akka.io/docs/akka-http/current/client-side/host-level.html#configuring-a-host-connection-pool

**Comment by dpratt** [comment]
As near as I can tell, this PR is ready to be merged.

I'd love it if you guys could get this in before the next release - my org really wants to upgrade to Scala 2.13 and this is the last thing blocking us. I suspect we're not the only people waiting on this as well.

**Comment by mar-kolya** [comment]
@dpratt 

Could you please clarify why why these renames are needed? IIRC those java classes were put into scala directory just to make compiler/order happy - there were implemented in Java. I'm actually surprised it builds and passes tests with this change.

Ass far as SuperPool goes - as far as I can see we had tests for it that looked legit. Is there anything that is wrong with the test that hides problem with the instrumentation?

**Comment by dpratt** [comment]
I suspect that the tests pass by accident, in that a SuperPool is exactly that, a pool of connections. When the flow is supplied with concurrent requests, they will likely be dispatched to different underlying connections, and the responses will be emitted by the flow in any ordering. The current instrumentation makes the incorrect assumption that they will be emitted in the order submitted, which is incorrect. This will cause responses to close spans completely unrelated to their actual request. Essentially, the flow does not respect ordering - if you give it a list of requests [req1, req2, req3, req4] the ordering of the responses is undefined. If they come back as [resp2, resp4, resp1, resp3] then the span timing (and other metadata attached to the span at close time such as the response code, or any error) will be wildly incorrect and the traces will be nonsensical. This is documented at the link I attached, and expected behavior. 

Additionally, the fact that the previous implementation worked with both Scala 2.11 and 2.12 was essentially an accident. It is compiled only against 2.11, and Scala has an explicit binary incompatibility across versions. Using artifacts compiled with mismatched versions has undefined or potentially even silently incorrect behavior, and is not supported. If you want the agent to bundle compiled Scala code to be used at runtime, you’ll likely need to have multiple versions of the instrumentation jar compiled against every supported Scala version, and then have the agent pick the right one at runtime.

Renaming the directory was just done as an esthetic cleanup since there’s no longer any actual Scala code in there.

**Comment by dpratt** [comment]
There’s an easy way to see the above behavior - make two routes, /a and /b in a test server. Have the implementation of /a pause for 500 milliseconds before returning, and have /b respond immediately. Then, submit requests to the SuperPool flow for /a and /b. You’ll see that the responses are emitted from /b and then /a, which causes the span for the /a request to be closed by the response for /b, and the /b span to be closed by the response for /a. The implementation as it stands today does not work.

On top of that, the fact that the compiled version of the instrumentation is linked against Scala 2.11 means that it is only guaranteed to work against Scala 2.11 at runtime. It’s a happy accident that linking it against Scala 2.12 doesn’t throw an exception, but there’s no guarantee that will actually work in the future. Similarly, attempting to use this against Scala 2.13 does not work - it blows up at instrumentation time.

**Comment by mar-kolya** [comment]
@dpratt I just wanted to clarify: there are essentially three changes:
* removed superpool instrumentation
* added muzzle test for new akka version
* renames for scala->java

I.e. there are no changes to specifically support new akka version, old code still works after some renames - is this correct?

**Comment by dpratt** [comment]
That’s precisely it.

**Comment by dpratt** [comment]
Don't want to be a bother - are there plans to merge this in for the next release?

**Comment by labbati** [comment]
HIi @dpratt first of all thanks a lot for the PR. Let me try to get sometime today or tomorrow for a final review and then we can merge.

**Comment by dpratt** [comment]
Any chance of this making 0.31.0?

**Comment by wuservices** [comment]
I'm using elastic4s for Elasticsearch from Scala with its Akka HTTP client. I was wondering why I couldn't see the HTTP requests, but I'm thinking it's due to lack of support for SuperPool, since I see that being [used in elastic4s](https://github.com/sksamuel/elastic4s/blob/v7.9.2/elastic4s-client-akka/src/main/scala/com/sksamuel/elastic4s/akka/DefaultHttpPoolFactory.scala#L28).

Sorry this is a bit off topic, but it seems like people here are the most familiar with Akka HTTP, so I just wanted to see if this is something that would make sense for me to open a feature request for and if that's what's missing for logging calls to the elastic4s code, or if there's some reason that just wouldn't be a reasonable request.

**Comment by tylerbenson** [comment]
@wuservices would you mind posting about this as a separate issue or [via support](mailto:support@datadoghq.com).

**Pull request merged**
