### PR TITLE
Support instrumentation of classes compiled with a target of 'jsr14'

### PR DESCRIPTION
**Pull request by mcculls**
The 'jsr14' target was a short-term option added between Java 1.4 and Java 6 to help JDK developers test and
migrate code to the generics language feature. It wasn't intended to be used in third-party applications but
it did get used in some OSGi frameworks who wanted to make generic-ready APIs while also supporting Java 1.4

This results in a classfile that has a bytecode version of 48 (Java 1.4) but also contains generic signatures.
Unfortunately this trips up Byte-Buddy when instrumenting because it thinks Java 5+ advice has been incorrectly
added to the Java 1.4 class (due to the generic signatures which actually come from the original bytecode).

To fix this we extend Byte-Buddy's TypeConstantAdjustment to also null out generic signatures from bytecode
compiled with a target of 1.4 or below. These signatures should already be null in the original class file,
it's only if the original source used generics and the class was compiled with a target of 'jsr14' that they
would need nullifying.

We also add a config option to switch back to the original Byte-Buddy TypeConstantAdjustment if necessary:
```
  -Ddd.jsr14.target.adjustment.enabled=false
```
```
  DD_JSR14_TARGET_ADJUSTMENT_ENABLED=false
```

### CODE REVIEW

**Review by devinsba — APPROVED** [review]
Seems like a straightforward solution to an odd problem

**Review by tylerbenson — APPROVED** [review]
Nice find.  Can I suggest reporting an issue to Byte Buddy?  I bet @raphw would find this interesting.

**Review by bantonsson — APPROVED** [review]

**Comment by raphw** [comment]
Id did some tests and wonder how this trips Byte Buddy? Is this due to the validation? Ideally, you do not run it in production systems to begin with but I adjusted that. Is there any other side-effect?

**Comment by mcculls** [comment]
Hi @raphw - yes it was triggering the assertions in `TypeWriter` that checked generics weren't used when rewriting a Java 1.4 class. I see you've adjusted these assertions which will avoid this issue - thanks!

https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/TypeWriter.java#L3339

We're not using the jsr14 class in the tracer, but a third-party application being traced had a couple of these classes and they weren't getting instrumented because of this (unfortunately they were also classes that really needed to be instrumented.)

I've only seen them in OSGi 4.3 applications (https://blog.osgi.org/2012/10/43-companion-code-for-java-7.html) and even there they didn't last very long - but it appears some are still being used in production, probably because no-one has needed to recompile the library containing them! Just goes to show how long things can stay around in software...

**Pull request merged**
