### PR TITLE
Enable OldObjectSample by default in dd.jfp

### PR DESCRIPTION
**Pull request by luhenry**
That is to bring the the Heap Profiler to GA.

### CODE REVIEW

**Comment by luhenry** [comment]
It's waiting on JDK 11.0.12 to be released with the latest performance fixes so that we can measure internally the performance impact of enabling it by default. Once we've validated that the performance impact is non-existent, we can enable this feature by default.

**Comment by dougqh** [comment]
> It's waiting on JDK 11.0.12 to be released with the latest performance fixes so that we can measure internally the performance impact of enabling it by default. Once we've validated that the performance impact is non-existent, we can enable this feature by default.

Does that mean we don't intend to enable old sampling by default on older JVMs without the performance fixes?

**Comment by luhenry** [comment]
> Does that mean we don't intend to enable old sampling by default on older JVMs without the performance fixes?

Yes. This was done in https://github.com/DataDog/dd-trace-java/pull/2858. The user can always overrides it manually but as part of dd.jfp, comprehensive.jfp, or minimal.jfp we are choosing not to enable events we know are slow OOTB. We want to keep this list to a minimum right now (native method sampling, allocation profiling, and heap profiling).

**Comment by luhenry** [comment]
Failures are related to dependencies which fail to be fetched. Merging nonetheless.

**Review by jbachorik — APPROVED** [review]

**Pull request merged**
