### PR TITLE
If process shuts down early then registration of shutdown hooks by JFR may fail

### PR DESCRIPTION
**Pull request by mcculls**
```
java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
	at jdk.jfr/jdk.jfr.internal.SecuritySupport.lambda$registerShutdownHook$8(SecuritySupport.java:316)
	at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:210)
	at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:207)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:430)
	at jdk.jfr/jdk.jfr.internal.SecuritySupport.doPrivileged(SecuritySupport.java:207)
	at jdk.jfr/jdk.jfr.internal.SecuritySupport.registerShutdownHook(SecuritySupport.java:316)
	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.<init>(PlatformRecorder.java:88)
	at jdk.jfr/jdk.jfr.FlightRecorder.getFlightRecorder(FlightRecorder.java:182)
	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:97)
	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:121)
	at com.datadog.profiling.controller.openjdk.OpenJdkController.createRecording(OpenJdkController.java:60)
	at com.datadog.profiling.controller.openjdk.OpenJdkController.createRecording(OpenJdkController.java:31)
	at com.datadog.profiling.controller.ProfilingSystem.startProfilingRecording(ProfilingSystem.java:135)
	at datadog.trace.util.AgentTaskScheduler$PeriodicTask.run(AgentTaskScheduler.java:241)
	at datadog.trace.util.AgentTaskScheduler$Worker.run(AgentTaskScheduler.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
To avoid leaking errors into the log we detect this and log a debug message instead.

### CODE REVIEW

**Review by bantonsson — APPROVED** [review]
Is this what's failing the `OSGi` smoke tests?

**Comment by mcculls** [comment]
@bantonsson yes - smoke tests run with profiling enabled, and the OSGi test doesn't run for long because the issues we're checking for in that test appear early on. We're also actively scraping the log for errors in that test which is why it's picking up this exception (which can happen when the randomized profiling startup delay coincides with the JVM shutting down.)

**Review by richardstartin — APPROVED** [review]

**Review by tylerbenson — APPROVED** [review]

**Review by jbachorik — APPROVED** [review]

**Review by bantonsson — APPROVED** [review]
Merge all the things!

**Comment by bantonsson** [comment]
🎉

**Pull request merged**
