### PR TITLE
Add a number of 'new' JFR events to be enabled by default

### PR DESCRIPTION
**Pull request by jbachorik**
# What Does This Do
Adds a few fairly new JFR events to the default dd.jfp file

# Motivation

# Additional Notes

Jira ticket: [PROF-8842]

[PROF-8842]: https://datadoghq.atlassian.net/browse/PROF-8842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by richardstartin — APPROVED** [review]

**Comment by KamilZemczak** [comment]
Hey, I'm using your dd-trace library and for the past few days, we have started seeing three types of logs in our logs:
```
Exception occurred during execution of event jdk.ContainerCPUThrottling(36236)
Exception occurred during execution of event jdk.ContainerCPUUsage(36234)
Exception occurred during execution of event jdk.ContainerConfiguration(36232)
```
 
We haven't changed anything recently, we haven't upgraded Java, and we haven't modified any configuration options. What could be causing this? How to "hide it"? Because it's cost a lot of for me:))

**Comment by KamilZemczak** [comment]
@jbachorik @richardstartin 

> Hey, I'm using your dd-trace library and for the past few days, we have started seeing three types of logs in our logs:
> 
> ```
> Exception occurred during execution of event jdk.ContainerCPUThrottling(36236)
> Exception occurred during execution of event jdk.ContainerCPUUsage(36234)
> Exception occurred during execution of event jdk.ContainerConfiguration(36232)
> ```
> 
> We haven't changed anything recently, we haven't upgraded Java, and we haven't modified any configuration options. What could be causing this? How to "hide it"? Because it's cost a lot of for me:))

**Comment by jbachorik** [comment]
Hi @KamilZemczak  - can you specify what is your JDK version and the environment?

These events are built-in JDK events - they should not be erroring out casually. If it is consistent and reproducible it would be worth of reporting to OpenJDK.

In the meantime, you could use `-Ddd.profiling.disabled.events=jdk.ContainerCPUThrottling,jdk.ContainerCPUUsage,jdk.ContainerConfiguration` to force-disable those events for the affected services.

**Comment by KamilZemczak** [comment]
@jbachorik 

Hey. First of all, thank you very much for the response!

The JDK we have is: 21. We have a system that uses Spring Boot; it is running on GCP (10 instances). Do you need more details?

Interestingly, after downgrading the log4j library from 2.24.1 to 2.24.0, the logs stopped appearing. But on another service, we have a lower version of log4j, and despite that, the logs are also appearing... The logs appear practically every second, an example of them: 
`[19431.976s][warning][jfr,system] Exception occurred during execution of event jdk.ContainerConfiguration(36698)`

Thanks for providing commands above. I will try to use it!

**Pull request merged**
