### PR TITLE
Remove alloc for a single class name

### PR DESCRIPTION
**Pull request by charliegracie**
The var args versions allocates an array for every call. Create
a version to handle single classNames

### CODE REVIEW

**Comment by charliegracie** [comment]
There are 3 instances of hasClassesNamed after this change. These instances in the form `hasClassesNamed("foo", "bar")` could be replaced with `hasClassNamed("foo").and(hasClassNamed("bar"))`. I am not sure if it is better to keep 2 versions of the Matcher to handle these instances or just use the conjunction. Any thoughts would be appreciated.

**Comment by richardstartin** [comment]
> There are 3 instances of hasClassesNamed after this change. These instances in the form hasClassesNamed("foo", "bar") could be replaced with hasClassNamed("foo").and(hasClassNamed("bar")). I am not sure if it is better to keep 2 versions of the Matcher to handle these instances or just use the conjunction. Any thoughts would be appreciated.

I think we should take every opportunity to replace declarative chaining with a simple for loop. 

I might have approached this slightly differently - if we made the field `resources` an `Object`, we could accept `String` or `String[]` in the constructor, then we could either do an `instanceof` check in `hasResources` or record what the type was in the constructor and switch/branch on it, casting appropriately. This would avoid having two classes.

**Comment by richardstartin** [comment]
@charliegracie I think a good change to make with this would be to remove all class loader matchers where the type matcher itself is a name based matcher.

**Comment by charliegracie** [comment]
> @charliegracie I think a good change to make with this would be to remove all class loader matchers where the type matcher itself is a name based matcher.

In this [commit](https://github.com/DataDog/dd-trace-java/pull/2631/commits/1c4382a2bee3351e94eb1ed7aaf93e04be62cb85) I removed all `classLoaderMatchers()` where the `typeMatcher` was a single `name()` call. Is this what you were talking about?

**Comment by charliegracie** [comment]
> I think we should take every opportunity to replace declarative chaining with a simple for loop.
Ok great me too. Do you think it is worth adding `hasNoClassNamed` and `hasNoClassesNamed` versions of `hasClassNamed` and `hasClassesNamed` so we can get rid of `not(hasClassNamed))` calls? If so we could also add `notNamed` to the NameMatcher.

> I might have approached this slightly differently - if we made the field `resources` an `Object`, we could accept `String` or `String[]` in the constructor, then we could either do an `instanceof` check in `hasResources` or record what the type was in the constructor and switch/branch on it, casting appropriately. This would avoid having two classes.

I quickly added a [commit](https://github.com/DataDog/dd-trace-java/pull/2631/commits/68399c69da4560aa5736d330df3493f6e583fb4b) that has a single class which can take a String[] or String parameter. I am not sure I like it but is it closer to how you would have approached it? Both implementations are available in the commit to compare.

**Comment by richardstartin** [comment]
Yes that's what I had in mind. The only advantage is that we don't have two classes if we want to treat one or many resources differently, but it's not a big deal. How significant is the allocation relative to the size of the change? It must be fewer than 80 one element arrays allocated based on the number of changed files.

**Comment by richardstartin** [comment]
> In this [commit](https://github.com/DataDog/dd-trace-java/pull/2631/commits/68399c69da4560aa5736d330df3493f6e583fb4b) I removed all classLoaderMatchers() where the typeMatcher was a single name() call. Is this what you were talking about?

Yes this is what I meant. The class loader matchers are more expensive than the type matchers they guard in these cases. We just need to be careful none of these are for correctness rather than optimisation.

**Comment by richardstartin** [comment]
```java
@Override
  public ElementMatcher<ClassLoader> classLoaderMatcher() {
    // prevents Runnable from being instrumented unless this
    // instrumentation would take effect (unless something else
    // instruments it).
    return hasClassNamed("akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask");
  }
```
should stay as it is, I think.

**Comment by charliegracie** [comment]
> ```java
> @Override
>   public ElementMatcher<ClassLoader> classLoaderMatcher() {
>     // prevents Runnable from being instrumented unless this
>     // instrumentation would take effect (unless something else
>     // instruments it).
>     return hasClassNamed("akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask");
>   }
> ```
> 
> should stay as it is, I think.

Why would this would need to stay as is? The classLoaderMatcher() and typeMatcher() look for the exact same name.

**Comment by richardstartin** [comment]
> Why would this would need to stay as is? The classLoaderMatcher() and typeMatcher() look for the exact same name.

It's not there to guard the type matcher, but impacts context store creation. The Akka concurrent instrumentations require `Runnable` to be instrumented in order to work, but we want to remove the general purpose `RunnableInstrumentation` eventually. This classloader matcher just prevents the context store from being created, unless another loaded instrumentation field injects `Runnable` or if Akka is actually present.

**Comment by charliegracie** [comment]
After discussing this with @tylerbenson offline I think it is better to just provide an overloaded version of `hasClassesNamed` that handles the case where there is a single `String` parameter. This makes it easier for people to use since there is only 1 API to remember and makes the changeset significantly smaller.

**Review by tylerbenson — APPROVED** [review]
Much better!

**Review by mcculls — APPROVED** [review]

**Review by bantonsson — APPROVED** [review]

**Pull request merged**
