### PR TITLE
Make Scala 2.10-2.12 Promise/Future behave the same way as Scala 2.13

### PR DESCRIPTION
**Pull request by bantonsson**
Cleans up a bit in the duplication of tests and makes Scala 2.10-2.12 Promise/Future behave the same as Scala 2.13.

In preparation for further changes to Promise/Future.

### CODE REVIEW

**Comment by richardstartin** [comment]
Can you provide some more high level explanation of the changes?

**Review by richardstartin — APPROVED** [review]

**Review by tylerbenson — APPROVED** [review]

**Comment by bantonsson** [comment]
So the high level change for 2.10-2.12 is that it now picks up the current scope, if there is not state stored for this `CallbackRunnable`, in the same way that Scala 2.13 does for `Promise.Transformation`. The rest is just trying to clean up the tests, so they can be reused and shared.

**Comment by randomanderson** [comment]
I think this deserves to be in the release notes.

**Comment by bantonsson** [comment]
@randomanderson You're definitely right. I was thinking of this a step towards the coming change, but that will be a bit out.

**Pull request merged**
