### PR TITLE
Add jdbc support for aws-mysql-jdbc driver

### PR DESCRIPTION
**Pull request by devinsba**
# What Does This Do

# Motivation

# Additional Notes

### CODE REVIEW

**Comment by Loganathanc** [comment]
i thought so... but it was not working. when i tried only those 2 classes alone.

**Comment by Loganathanc** [comment]
i have tried with your snapshot jar today and its working fine... please push the changes in upcoming release. Thanks

**Comment by devinsba** [comment]
Thanks for the update. Your code was missing two of the classes but your changes made me think it would just work now after the first bug we fixed.

**Comment by Loganathanc** [comment]
when will be part of release? any idea?

**Comment by Shyam-1990** [comment]
@devinsba : Any ETA on adding this change to the release. I have created ticket for the DD support team as well.

**Comment by devinsba** [comment]
Hi, sorry. There should be a release this week.

**Pull request merged**
