### PR TITLE
Remove span.origin.type tag

### PR DESCRIPTION
**Pull request by richardstartin**
removes the `span.origin.type` tag

### CODE REVIEW

**Comment by richardstartin** [comment]
I would be in favour of entirely removing this tag

**Comment by richardstartin** [comment]
The GlassFish test failures are incomprehensible and should not have been caused by this change

**Comment by tylerbenson** [comment]
I am also not opposed to removing the tag now either.

**Comment by richardstartin** [comment]
>I am also not opposed to removing the tag now either.

@tylerbenson I dropped the commits and removed the tag. Let's leave this open for a few days and see if anyone requests we keep this tag.

**Review by mcculls — APPROVED** [review]
LGTM

**Review by bantonsson — APPROVED** [review]
🎉

**Comment by aquiladayc** [comment]
hey team 👋  My customer noticed this tag was missing after upgraded java tracer and I found this PR. Can you share some context why it's removed please? 
Also, is it possible to get this tag by adding env variable or something?

**Comment by tylerbenson** [comment]
@aquiladayc We removed it because it seemed to provide more noise than value.  Perhaps you could provide more details on what was helpful/useful about this tag?

**Comment by aquiladayc** [comment]
@tylerbenson as discussed with customer, they don't need it for now. Thanks!

**Pull request merged**
