### PR TITLE
Initial support for setting Event Sample Rate via tags

### PR DESCRIPTION
**Pull request by tylerbenson**
This only adds the API, no changes to the integrations.

### CODE REVIEW

**Comment by tylerbenson** [comment]
@brettlangdon It would be either in the `SpanBuilder` similar to this:
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java#L50

or directly on the span similar to this:
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/spring-web/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java#L74-L75

**Comment by realark** [comment]
Code looks good!

Question about the rfc. The wording `Integrations enabled by default must tag only the first Span` seems to imply that we should set the `metrics` map for only the topmost span for a particular service. We're currently setting the `metrics` map for the span which happens to get the tag set.

For example, let's say we have this trace:
```
span0 (serviceName = "java-web")
 |
span1 (serviceName = "java-web")
 |
span2 (serviceName = "mongodb")
```

If a user calls `span1.setTag(EVENT_SAMPLE_RATE, 0.8)`, which span is supposed to get the `metrics` map set? What about `span2.setTag(EVENT_SAMPLE_RATE, 0.5)`? Currently the code will set the metrics for span1 and span2 respectively. That's correct, right?

cc @palazzem @brettlangdon

**Comment by brettlangdon** [comment]
@realark that description is correct.

The wording for the RFC relates to the implementation of our custom integrations. It means that for a particular integration, let us say Spring, which has a root span of `spring.request`, we want to only set the tag/metric on the top `spring.request` span for that integration.

Does that make sense?

**Comment by realark** [comment]
Thanks @brettlangdon. Just to confirm, in my example, setting the metrics on `span1` and `span2` is **incorrect**, right? The correct behavior should be `span0` and `span2` get their `metrics` map set, and `span1` does not, since it's not a "service root" span.

@tylerbenson I think that means this PR isn't compliant with the RFC, since the metric will be set on whichever span `setTag` is invoked on, rather than the "service root" span.

**Comment by brettlangdon** [comment]
@realark yes, that is correct.

I was saying the description was correct because the metrics map should be set on the span which you set the tag on.

But you are correct, to be compliant with the RFC we should only set the tag/metrics map on the service root span, so `span0` and `span2` in the example you shared.

**Comment by palazzem** [comment]
Just to clarify the behavior a bit. I've updated the RFC to state what should be the behavior: https://github.com/DataDog/architecture/pull/287

The bottom line is this API should set the "metric" only to the ``Span`` where `setTag()` is invoked. So to recap the initial example:
```
span0 (serviceName = "java-web")
 |
span1 (serviceName = "java-web")
 |
span2 (serviceName = "mongodb")
```

* If you call `span1.setTag(EVENT_SAMPLE_RATE, 0.8)` you will set the metric for `span1`
* If you call `span2.setTag(EVENT_SAMPLE_RATE, 0.5)` you will set the metric for `span2

This PR reflects exactly this behavior (at least the logic), so it's good to go.

**Pull request merged**
