### PR TITLE
Add support for `TRACE_HTTP_CLIENT_ERROR_STATUSES`

### PR DESCRIPTION
**Pull request by mhlidd**
# What Does This Do
Add support to handle `TRACE_HTTP_CLIENT_ERROR_STATUSES` tag as well as the original `HTTP_CLIENT_ERROR_STATUSES` tag in efforts to be more consistent with the tags from other languages.
# Motivation
Our goal is to make the implementation of configuration variables consistent for all languages as part of the config consistency effort listed in the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit).
# Additional Notes

# Contributor Checklist

- [ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ ] Squash your commits prior merging or merge using GitHub's [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [ ] Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an issue.  
  Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the issue
- [ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or behavior

Jira ticket: [APMAPI-477](https://datadoghq.atlassian.net/browse/APMAPI-477)

[APMAPI-477]: https://datadoghq.atlassian.net/browse/APMAPI-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Following our discussion, I made a PR to test config alias priority here: #7706

**Review by PerfectSlayer — COMMENTED** [review]
LGTM

**Comment by mhlidd** [comment]
@PerfectSlayer Can I get the approving review to merge this PR? 🙇‍♂️

**Comment by PerfectSlayer** [comment]
Looks like I only _comment_ where I meant to _approve_ 😅

**Review by PerfectSlayer — APPROVED** [review]

**Review by ygree — APPROVED** [review]

**Pull request merged**
