### PR TITLE
Refactor how we apply custom transformers

### PR DESCRIPTION
**Pull request by mcculls**
# What Does This Do

This refactors how instrumentations apply whole-type advice.

Previously an instrumenter would override the `transformer` method and pass back a single advice:
```
  @Override
  public AdviceTransformer transformer() {
    return new VisitingTransformer(new TaintableVisitor(this.instrumentedType()));
  }
```
Now an instrumenter overrides the `typeAdvice` method and registers its advice with the type transformer:
```
  @Override
  public void typeAdvice(TypeTransformer transformer) {
    transformer.applyAdvice(new TaintableVisitor(this.instrumentedType()));
  }
```
As a convenience the type transformer can accept both `TransformingAdvice` or `AsmVisitorWrapper`

(the latter is automatically wrapped with `VisitingAdvice`)

# Motivation

This provides a similar API for applying whole-type advice compared to applying method advice:
```
   @Override
   public void methodAdvice(MethodTransformer transformer) {
     transformer.applyAdvice(named("getName").and(takesArguments(0)), className + "$GetNameAdvice");
     transformer.applyAdvice(named("getValue").and(takesArguments(0)), className + "$GetValueAdvice");
   }
```

This also aligns better with how OTel register their whole-type advice, namely via a registration callback:
```
  @Override
  public void transform(TypeTransformer transformer) {
    transformer.applyTransformer(
        // ...
```

# Additional Notes

As part of this refactoring I took the opportunity to align some of the naming and do some minor clean-up.

Jira ticket: [AIT-9480]

[AIT-9480]: https://datadoghq.atlassian.net/browse/AIT-9480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nikita-tkachenko-datadog — APPROVED** [review]

**Review by richardstartin — APPROVED** [review]
for the changes to profiling instrumentations

**Review by PerfectSlayer — APPROVED** [review]
LGTM :+1:

> do some minor clean-up.

Does removing Vert.x files (`HttpServerRequestInstrumentation.java` and `HttpServerRequestInstrumentation.java`) also part of the cleanup?
What about the two remaining `BlockingExceptionHandler.java` files? Should we remove them too?

**Comment by mcculls** [comment]
> LGTM 👍
> 
> > do some minor clean-up.
> 
> Does removing Vert.x files (`HttpServerRequestInstrumentation.java` and `HttpServerRequestInstrumentation.java`) also part of the cleanup? What about the two remaining `BlockingExceptionHandler.java` files? Should we remove them too?

Thanks - I noticed those files under `dd-java-agent/instrumentation/vertx-web-4.0/main/java/` (note the missing `src`) and realized they were leftovers from a different PR, because they weren't touched when I refactored the API in IntelliJ

I've removed the unused `BlockingExceptionHandler.java` files too leaving just the real files under `.../src/main/java/...`

**Comment by mcculls** [comment]
> PS: As a future improvement we might want to truly separate `HasTypeAdvice` and `HasMethodAdvice` so we are not forced to implement both (maybe there are performance constraints during startup making it better to join them in `HasAdvice`)

Thanks for the suggestion - I have a further refactoring which might make that easier

**Review by amarziali — APPROVED** [review]
thanks for the refactoring

**Pull request merged**
