### PR TITLE
Misc upgrades.

### PR DESCRIPTION
**Pull request by tylerbenson**
When I tried upgrading to Byte Buddy 1.8.0 I get the following error in `JerseyTest`:

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at net.bytebuddy.jar.asm.AnnotationWriter.computeParameterAnnotationsSize(AnnotationWriter.java:363)
	at net.bytebuddy.jar.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2036)
	at net.bytebuddy.jar.asm.ClassWriter.toByteArray(ClassWriter.java:426)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2946)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8951)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9352)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9315)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9093)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9671)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9621)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9240)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:6216)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6071)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4252)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:8307)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:10006)
	at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:71)
	at datadog.trace.agent.test.AgentTestRunner.agentSetup(AgentTestRunner.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:188)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
...
```

As a result, I'm leaving it at 1.7.11.

cc/ @raphw

### CODE REVIEW

**Comment by tylerbenson** [comment]
I'll work on these errors tomorrow.

**Comment by raphw** [comment]
Thanks for making me aware of this. I am investigating. I cannot exclude that this is actually a bug in ASM 6.1 which changed the way how parameter annotations are represented to a method visitor. I will let you know once I found out more.

**Comment by raphw** [comment]
I just pushed a few changes and also updated ASM to 6.1.1 which was just released yesterday. I struggle to reproduce the issue as a unit test but could you build Byte Buddy from master and see if the issue is resolved?

When I patch your build to use my local Maven repository to use `1.8.1-SNAPSHOT`, I get further but the build implodes due to some shadow jar plugin issues at some point. But I wonder if the unit test completes as expected.

**Comment by raphw** [comment]
I released 1.8.1 which should fix that issue.

**Comment by tylerbenson** [comment]
@raph, ok thanks. I’ll try tomorrow.

**Comment by tylerbenson** [comment]
@raphw that seemed to work.  Thanks for fixing that!

**Pull request merged**
